{% set python_min = '3.10' %}
{% set version = "24.7" %}

package:
  name: pysal
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pysal/pysal-{{ version }}.tar.gz
  sha256: 7cf9d520b21c3c5db15d08d0f670e6b1cc4f029df46a31b9ddaee2d4b1210c8b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - libpysal >=4.12.0
    - access >=1.1.9
    - esda >=2.6.0
    - giddy >=2.3.5
    - inequality >=1.0.1
    - pointpats >=2.5.0
    - segregation >=2.5
    - spaghetti >=1.7.6
    - mgwr >=2.2.1
    - momepy >=0.7.2
    - spglm >=1.1.0
    - spint >=1.0.7
    - spreg >=1.5.0
    - spvcm >=0.3.0
    - tobler >=0.11.2
    - mapclassify >=2.7.0
    - splot >=1.1.5.post1
    - spopt >=0.6.1

test:
  requires:
    - python {{ python_min }}
  imports:
    - pysal
    - pysal.viz
    - pysal.explore
    - pysal.model
    - pysal.lib
  # See https://github.com/conda-forge/pointpats-feedstock/pull/4
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: http://pysal.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Library of spatial analysis functions
  description: |
    PySAL(Python Spatial Analysis Library) for spatial data science and the development of high level applications.
  doc_url: http://pysal.org/pysal
  doc_source_url: https://github.com/pysal/pysal/blob/master/doc/source/index.rst
  dev_url: https://github.com/pysal

extra:
  recipe-maintainers:
    - knaaptime
    - martinfleis
    - jGaboardi
    - sjsrey
    - ocefpaf
    - mariusvniekerk
    - marcelotrevisani
