{% set version = "2.3.0" %}

package:
  name: pysal
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pysal/pysal-{{ version }}.tar.gz
  sha256: 6f15a1432ff6805edd53ba6a5444f9af4ba2acd8a78f8f678c8bc09ffb0debe1

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - access >=1.1.1
    - coverage
    - esda >=2.3.1
    - giddy >=2.3.3
    - inequality >=1.0.0
    - libpysal >=4.3.0
    - mapclassify >=2.3.0
    - mgwr >=2.1.1
    - pointpats >=2.2.0
    - pytest
    - pytest-cov
    - python >=3.7
    - python-dateutil <=2.8.0
    - segregation >=1.3.0
    - spaghetti >=1.5.0
    - spglm >=1.0.7
    - spint >=1.0.6
    - splot >=1.1.3
    - spreg >=1.1.1
    - spvcm >=0.3.0
    - tobler >=0.3.1
    - urllib3 <1.25

test:
  imports:
    - pysal
    - pysal.viz
    - pysal.explore
    - pysal.model
    - pysal.lib

about:
  home: http://pysal.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Library of spatial analysis functions
  description: |
    PySAL(Python Spatial Analysis Library) for spatial data science and the development of high level applications.
  doc_url: http://pysal.org/pysal
  doc_source_url: https://github.com/pysal/pysal/blob/master/doc/source/index.rst
  dev_url: https://github.com/pysal

extra:
  recipe-maintainers:
    - sjsrey
    - ocefpaf
    - mariusvniekerk
    - marcelotrevisani
